language: node_js

node_js:
  - 10
  - 8
  - 6

branches:
  only:
    - master

stages:
  - test
  - name: release
    if: type != pull_request AND branch = master

jobs:
  include:
    - stage: release
      script:
        - npm install --no-save semantic-release-tamia
        - >-
          npx semantic-release --analyze-commits semantic-release-tamia/analyzeCommits --verify-release semantic-release-tamia/verifyRelease --generate-notes semantic-release-tamia/generateNotes
